phoenixframework/phoenix_guides

- D_controllers.md
- suggestion from phoenixframework.org
> remove comma from sigil, because sigil

- X_mix-tasks.md
@jeregrine and @chrismccord (and anybody else following along at home), since I created the v0.7.2 tag, if I commit new 0.7.2 material, I've been doing the following.
- git co v0.7.2
- git cherry-pick the-commit-i-care-about
- git tag -f v0.7.2
- git push -f origin v0.7.2
With this, I am hopeful that the v0.7.2 tag actually means what it says, and that master better reflects Phoenix master. I bring this up now because this PR is clearly for master. Please let me know if you have any questions or comments.
> upgrading phoenix.start to phoenix.server

- G_channels.md
The Github link no longer has content relevant to the mentioned #links.
> Updated links from github to phoenixframework.org

- B_adding_pages.md
- G_channels.md
- X_mix-tasks.md
Remove Phoenix version number for links to phoenixframework.org.
> Fix links to phoenixframework.org

- G_channels.md
- changes code, return values and wording to match Phoenix 0.9.0
> Refurbish Channel Guide for Phoenix 0.9.0

- A_up_and_running.md
- `mix phoenix.new` only takes one argument
- the task prompts us to install mix dependencies as well as brunch.io dependencies
> refurb for v0.10.0

- L_advanced_deployment.md
The original line symlinked whole `sites-available` directory, which results in nginx giving an error:
```
"/etc/nginx/sites-enabled/sites-available" failed (21: Is a directory)
```
> Fix nginx setup steps

- G_channels.md
- fixes the immediately broken instructions
- still missing broadcasting to external topics (via controllers and channels), which will be handled in another PR
> refurbish channel guide for v0.10.0

- G_channels.md
Let's users know that we're only using subscribers/2 for expedience in this demo, and that we shouldn't ever use it in our applications.
I'm hoping that this addresses your concerns @chrismccord. Please let me know if you have additional edits that you'd like to make.
> Warnings About using subscribers/2 in Channel Guide

- A_up_and_running.md
The installation information link is currently pointing to the first page of the getting started instead of the installation page itself.
> Fix Elixir install information link

- H_ecto-models.md
This PR contains a couple of typo fixes and some larger changes to provide more culturally accepting examples.
Using language like "clearly", "obviously", and
"basically" is a common habit and is not intended
to be negative, but it can be offputting when
found in guidance as the concepts described are
frequently neither clear nor obvious for newcomers.
It's also redundant, as if it were obvious we wouldn't
be putting it in the documentation.
This change removes the split of "first name" and
"last name" with just a "name" field, and adds a
"bio" field to use as an example for length
validation.
There's two main reasons for this change:
1. The idea of a neat first name and last name
is not as universal as we might think, and the
benefit gained from having separate fields is
small against …
> Improvements to ecto guide

- 0_overview.md
When viewing In github the dependencies listed were poorly formatted and it was unclear which paragraph belonged to which item especially for the second paragraphs for node.js, postgres, and inotify-tools
> updated dependencies formating

- B_adding_pages.md
- C_routing.md
- E_views.md
- F_templates.md
- H_ecto-models.md
- J_config.md
- README.md
- X_mix-tasks.md
Headings should have a space between the # and the content, or they won't
render correctly on the Phoenix framework website.
> Fix all headings so they should render correctly on Phoenix website

- A_up_and_running.md
- X_mix-tasks.md
This includes new, more direct wording about brunch.io dependencies. It also introduces this new wording _before_ instructions to issue the `mix phoenix.new` command.
closes #247
> Better Explanation of Brunch.io Dependencies

- L_advanced_deployment.md
- set the port statically to 8888
- offer guidance for setting the port via environment variable
- add instructions to run `MIX_ENV=prod mix phoenix.digest` before creating release
closes #268
> Fix Muddled Production Config in Advanced Deployment

- DD_Plug.md
Tho, I'm not sure what the indentation policy is for 90 char lines.
> Fixing locale example to set conn var

- deployment/I_exrm_releases
I had trouble getting nginx not to cut the connection and return a 400 to the client without the following `Upgrade` and `Connection` headers.
> Add nginx upgrade headers to prevent cutting connection.

- H_ecto-models.md
Wrote a little blurb on how to declare related data models for your models. Please let me know if this is even the convention we are suppose to follow for doing relationships (I hope so, because it's how I've been doing it). If I'm off the mark, please let me know and I will dutifully correct.
Oh yeah, I have a question: what's the convention for deleting dependent models?
Should we alias the Repo and do it in the model using callbacks like so:
```elixir
defmodule App.User do
use App.Web, :model
alias App.Repo
after_delete :destroy_posts
schema "users" do
has_many :posts, App.Post
end
def destroy_posts(%{model: model}) do
Repo.delete_all model.posts
end
end
```
Have the callback somewhere that already gets the Repo?
```elixir
defmodule App.User do
use App.Web, :model
after_delete …
```
> Section on how to use has_many and belongs_to for ecto models

- B_adding_pages.md
- DD_Plug.md
- D_controllers.md
- introduction/E_installation.md
0.14 release is imminent and I believe I addressed all relevant changes. @lancehalvorsen we did away with `plug :action` and thus `plug :render`, so I reworked the examples around this. You might want to double check the flow. Thanks!
> Sync with 0.14 release

- B_adding_pages.md
- E_views.md
- G_channels.md
- bonus_guides/D_mix_tasks.md
Sorry for not doing that [before](https://github.com/phoenixframework/phoenix_guides/pull/306). This PR replaces all occurrences of `application.html.eex`.
> Replace all occurrences of 'application.html.eex' with 'app.html.eex'

- introduction/E_installation.md
I'm not sure if this is the best place to add this paragraph to, but this is a pretty annoying error I've seen a few people running into.
Someone could argue that this is more of a brunch/nodejs problem, but I think it is fair that we provide some troubleshooting help since there's a decision to go with brunch as the default asset management tool.
> Add nodejs-legacy instructions for Debian users

- deployment/I_exrm_releases
In the documentation under Deployment, in the section showing the Upstart script (http://www.phoenixframework.org/docs/advanced-deployment#section-setting-up-our-init-system), the Upstart script also requires definition of the app HOME, otherwise the app won't start under Upstart. I have just experienced this bug myself, and it has also been reported elsewhere (see bitwalker/exrm#61). The Upstart script needs the following additions (using the directory from the doc example):
env HOME=/app
export HOME
> Update Upstart script to add app HOME.

- introduction/E_installation.md
A Windows user had trouble with this. It wasn't clear that their installation of io.js would not be sufficient to get Phoenix to work, even though it says it is npm compatible.
(We did not try to debug why io.js wasn't working, the user simply installed node.js and went on.  It's possible it *might* work, if someone puts in the time to figure it out.)
> Note that io.js is not known to work in place of node.js

- B_adding_pages.md
This has come up a couple of times in the irc channel.  After users match and get into an action, they wonder how to access all of the other things in the params match.
I intentionally flipped the elements of the pattern match around so that it does not look like assignment.
Do you think this belongs here, or perhaps on the controllers page instead?
> Show how to access the entire map of params in an action

- deployment/E_heroku.md
**WIP**
This is not 100% done yet but I wanted to get some early feedback while I was finishing/polishing it.
In the last section I plan to add something about running `iex` console and running migrations.
I'm also wondering whether to use an app with Ecto as an example (instead of the Phoenix welcome app).
> Adds Heroku deploy guide

- H_ecto_models.md
Reflect that phoenix now generates controller using the banged methods for CUD operations.
Don't know if it ought to be noted somewhere why they're used but I feel someone with better knowledge of Phoenix should write that (I'm a first timer just going through the docs).
> Update ecto models with banged insert/update/delete

- deployment/E_heroku.md
Add missing word in Heroku deployment guide.
> Fix phrase: can take of that → can take care of that

- deployment/E_heroku.md
When following the Heroku directions, I couldn't get my app to boot without first setting the `HOST` and `PORT` env vars.
I added a note to this effect, but I'm not sure if there's a better/more dynamic way of retrieving these from the Heroku environment without having to set them manually.
> Heroku: Add note on setting HOST and PORT config vars

- G_channels.md
I think it is important to mention socket assigns when talking about channels.
> Mention Phoenix.Socket.assign/3 in the channel guide

- G_channels.md
Without `import {Socket} from "deps/phoenix/web/static/js/phoenix"` in app.js, the browser console will raise:
```
ReferenceError: Can't find variable Socket
```
While importing directly into app.js seems to be the simplest solution, you could also:
```
import socket from "./socket"
```
Though I believe this would require a bit more tinkering and code rewriting to get it to work (a tad over my head right now).
Issues I've ran into with the alternative method - importing socket.js into app.js:
1. line 57 `let channel = socket.channel("topic:subtopic", {})` errors because of an unmatched topic.  Simple fix, just change the topic to: `"rooms:lobby"`
2. Looks like it's expecting a token.  A little over my head for this early in the docs :)
```
[Error] WebSocket connection to …
```
> import socket from deps/phoenix/web/static/js/phoenix

- H_ecto_models.md
Update the example mix command to include the table name after references, otherwise mix will generate the error:
```
** (Mix) Phoenix generators expect the table to be given to user:references.
For example:
mix phoenix.gen.model Comment comments body:text post_id:references:posts
```
> Add table name to references

- bonus_guides/G_static_assets.md
Because Babel already supports JSX, and Phoenix includes Babel support out of the box, it is misleading to mention JSX as something you can plugin if you need it. It is already there.
> Talking about Brunch plugins, mention TypeScript instead of JSX

- G_channels.md
A few colleagues came to me asking why their websocket didn't work. They followed the guide to the letter, but in the `web/channels/user_socket.ex` example file, we omit the required callbacks and `transport` setting. This PR simply includes those missing bits of code so that a new user can follow the channel guide and get a working websocket implementation up and running without having to look for the code represented by the `...`.
> add callbacks to example socket

- deployment/I_exrm_releases.md
It includes a missing "=" in order to make the script valid.
The script was validated with the `init-checkconf` command.
This also includes a small change in the name of upstart script for the
example application. Upstart should lookup the script by its name, so
the command `start hello_phoenix` will use the `/etc/init/hello_phoenix.conf` file.
> Fix upstart script at Advanced Deployment section

- bonus_guides/M_custom_errors.md
It took me a little while to understand that `ErrorView` was not working because
my `dev.exs` did not get recompiled.
I therefore added a little note about this in the relevant section.
> Add note about displaying custom errors.

- C_routing.md
includes elimination of a typo in the "multiple socket handlers" code example
> C_routing.md edits

- G_channels.md
Since some things have changed since the channels guide was written, I updated some of the code samples and a bit of the description so the guide matches Phoenix 1.0.2.
To make sure the code in the guide matches the current Phoenix version, I started out by generating a Phoenix 1.0.2 app named `HelloPhoenix` (like in the getting started guide) and worked from there. This means some small things changed, like the added `, otp_app: :hello_phoenix` in `lib/hello_phoenix/endpoint.ex
I tried to use as much of the generated code (like `lib/hello_phoenix/endpoint.ex`, `web/socket/user_socket.ex`, and `web/static/js/socket.js`) as possible. This means, for example, that all socket-related javascript code moved from `web/static/js/app.js` to `web/static/js/socket.js`, simply because a lot of the …
> Update the channels guide to match Phoenix 1.0.2

- G_channels.md
During ElixirConf, Chris McCord made mention of these clients to consume channels. This PR adds (AFAIK) the correct links to the most up-to-date/supported projects. I have no idea what the best C# client is, but [this blog post](http://www.phoenixframework.org/blog/phoenix-10-the-framework-for-the-modern-web-just-landed#beyond-the-browser) references it.
* contributed during the "How to contribute to Elixir and Phoenix" talk during ElixirConf
> Add links to iOS and Android channel clients

- deployment/E_heroku.md
All Heroku applications are hosted under `herokuapp` domain so each of them looks like `app-name.herokuapp.com`. [heroku.com](http://heroku.com/) is only for accessing a dashboard and no user apps are hosted as its subdomain.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/phoenixframework/phoenix_guides/387)
> Added correct Heroku url

- D_controllers.md
- E_views.md
1 Fixed a few typos: were -> was
2 Updated the html in the Views guide to match the latest Phoenix version (1.0.3)
3 Updated a few words in the Views guide
> Fixed a few typos and updated views guide

- testing/A_introduction.md
* Remove the "==> ranch (compile)" and  "Generated hello_phoenix app"
lines and the three dots from the first test run output to avoid
confusion with the four dots for the running tests. Now the output
matches the output you'd get after having compiled before, like the rest
of the test output in the guide.
* Add `test/views/layout_view_test.exs` to the `tree test` output
* Remove the "Create the database..."-comment in test/test_helper.exs,
as it's been removed in
https://github.com/phoenixframework/phoenix/commit/fcdc47a5ae19c00fe00ccb83c717c3c95af8685e.
* Add `end` tags to the `test/views/error_view_test.exs` code blocks
* Include the full output for `$ mix test
test/views/error_view_test.exs:12`
* Add a `$` before `mix test --exclude error_view_case`
* Include the `import …
> Fixes to the testing introduction guide

- bonus_guides/V_learning_elixir.md
"Hebert" should be "Hébert" according to the [cover of Learn You Some Erlang](http://www.amazon.com/Learn-Some-Erlang-Great-Good/dp/1593274351).
:heart: fellow Herokai.
> Add acute accent to Fred Hébert's surname

- deployment/E_heroku.md
Though `/www-header` works, it's actually an artifact of legacy Heroku code. This update makes the link more clear by removing the path.
source: I work on the Heroku www & signup apps.
> Update link to Heroku sign up

- E_views.md
- H_ecto_models.md
- testing/A_introduction.md
1 In Ecto Models guide, for the second sentence on line 551 of Ecto Models guide, since the sentence has `has_one` as the subject, it feels more nature for the except clause to start with `it`
2 In Ecto Models guide, for the first sentence under subtitle `Working with Callback Hooks`, the main clause `many web applications require moderation for user submitted content` feels unrelated to the part before it. So I tried to edit it. But other editing suggestions are most welcome for this.
3 In Testing Introduction guide, fixed the text for the link to Ecto Models guide
Please let me know what do you think @lancehalvorsen . Thanks!
> minor updates in Ecto Models guide and Testing Introduction guide

- bonus_guides/G_static_assets.md
- testing/E_models.md
1. In Testing Models guide, the string length returned by long_string/1 function is `length+1`, which is probably not intended.
2. Updated some wording in Static Assets Guide.
And also the last section of Testing Models Guide, `Generating an HTML Resource` has already been covered in Ecto Models Guide. If the repetition is unnecessary, I can remove this section as well. Thanks!
> Fixed typo in Testing Models guide

- testing/A_introduction.md
Very small issue, , the code block got included in the `<` quote,  which also affects normal text rendering at the next line. 
before:
after:
> Fix the code block got included in quote

- testing/A_introduction.md
Here's the rest of the fixes to the testing introduction guide, in the "Generating mode files" section:
- Add a `$` before `mix test --exclude individual_test:nope`
- Remove the "(lots ofo compilation)" line and use `...`, like in the
rest of the guide, for consistency.
- "we already have fifteen tests" has become "sixteen", as there are 2
model tests, 11 controller tests and 3 view test after going through
the whole guide
- Did *not* add the missing newline on line 225, as PR #398 already
fixes that
Here's the example app I used to update the code blocks and command line output; https://github.com/jeffkreeftmeijer/phoenix_testing_example.
> Fixes in "Generating More Files" in the testing introduction

- testing/A_introduction.md
Alright, just one more for the testing introduction. These seem to have slipped through in yesterday's pull request, sorry about that.
* Add the "Randomized with seed"-line to the first test's output
* Update the "Add the resource to the proper scope in web/router.ex:"
and "and then update your repository by running migrations:" messages
to the ones used in Phoenix 1.0.3
* Use 16 dots instead of 15 in the final test's console output
> Three minor fixes to the testing introduction

- bonus_guides/P_using_ssl.md
Relative paths begin at the root of the project, not `priv/`, when specifying otp_app key.
closes #395
> Update SSL Guide Relative Path Usage

- bonus_guides/J_sessions.md
It was corrected so as to be the same as the file actually is generated.
> change 'use' line of session example

- bonus_guides/I_sending_email.md
The missing comma creates the following error:
```
** (Mix.Config.LoadError) could not load config config/config.exs
** (SyntaxError) config/config.exs:29: syntax error before: mailgun_key
```
This pull request addresses a minor problem in the "sending email" documentation that can be a hurdle to newer people to phoenix as it is subtle and completely breaks a persons phoenix app.
> fix missing comma in email config

- bonus_guides/V_learning_elixir.md
- introduction/A_overview.md
I think now that it http://elixir-lang.org/getting-started/introduction.html  is correct URL
> fix URL of elixir guides

- bonus_guides/V_learning_elixir.md
- deployment/E_heroku.md
- deployment/I_exrm_releases.md
After seeing #408, I used [this little script](https://gist.github.com/jeffkreeftmeijer/5e36a0cfa7e2c735386e) to check the rest of the urls in the guides. 
* ~~Link to the sign up page from the email guide, and replace occurences
of "mailgun.com" with "Mailgun".~~ moved to https://github.com/phoenixframework/phoenix_guides/pull/411
* Use https links to pragprog.om, manning.com and nostarch.com
* Update links to https://www.nginx.com
* Use confreaks.tv instead of .com
* Use elements.heroku.com/addons instead of addons.heroku.com
* Switch to hexdocs.pm for exrm's documentation
> Update broken and 301'-ing links

- testing/E_models.md
As promised in #406;
- Update output for `mix.gen` to Ecto 1.0.6.
- Display the comment at the end of `web/router.ex` to add context and
not have to break the file up twice.
- Remove a double space.
> Update the "Generating .." section in the models testing guide

- bonus_guides/I_sending_email.md
- Link to the sign up page from the email guide
- Use "Mailgun" to refer to the service
- Use `mailgun` to refer to the package
- Use `:mailgun_domain` and `:mailgun_key` to refer to `mailgun`'s configuration options
From @lancehalvorsen in https://github.com/phoenixframework/phoenix_guides/pull/409#issuecomment-148973105:
> Originally, I had used "mailgun.com" to make it painfully obvious when we were talking about the service rather than "mailgun" the package. Do you (or anybody else who might be watching) feel that using "Mailgun" for the service and "mailgun" for the package is clear enough?
I think using "Mailgun" to refer to the service and `maligun` to refer to the package is clear enough, especially if we wrap `maligun` in `<code>` tags.
> Differentiate between "Mailgun" and `mailgun`

- F_templates.md
I've updated the templates testing guide to make sure the code blocks are clear and accurate, fix some typos and do some styling fixes and in line with the rest of the guides:
* Change "…what they […] should be - files…" to "…what they […] should
be: files…"
* "…generates `web/web.ex` file…" => "…generates a `web/web.ex file…"
* Explicitly state that "the main view" is in `web/web.ex`
* Add module lines around code blocks (like `defmodule HelloPhoenix.PageController do`
and `end`) to add context and indent accordingly.
* Display the comment at the end of web/router.ex to add context and not have to break the file up twice.
* Use `html` instead of `elixir` as the info string for template code blocks.
* Remove trailing newlines in code blocks
* Add missing newlines after code blocks
* …
> Update the templates guide

- F_templates.md
While interesting to know, explaining how to change the template root directory is out of the scope of the templates guide, as changing the template root is something you should probably only do when you're more familiar with the framework. Also, putting it at the start of the guide like this is confusing, as it's not completely clear if the reader should do anything with the template root directory or not. It might be
a good idea to move this elsewhere.
I'm opening a separate pull request for this instead of throwing it in with #422 to have some room for discussion wether this should be removed or not.
> Don't explain how to change the template root directory

- F_templates.md
This seems to have slipped through when working on #422.
* Mention the filename (`web/templates/page/test.html.eex`) in the
paragraph above the last code block, as moving one file and editing
another might be confusing
* Use `html` instead of `elixir` as the info string for the last code
block
> Minor fixes to the templates guide

- E_views.md
I noticed http://elixir-lang.org/docs/stable/eex/EEx.html uses the EEx case while the guides had it as Eex
> Fix case to match project docs: Eex -> EEx

- A_up_and_running.md
* Use "let's run `mix phoenix.new`" instead of "let's call
`phoenix.new`"
* Show more output from the `mix phoenix.new` task and include the
`Fetch and install dependencies? [Yn]`-line
* Split the output from `mix phoenix.new` only once, at the "Fetch and
install dependencies"-prompt
* Split up `cd`-ing into the project directory, creating the database
and starting the Phoenix server and include output
* Update output from `mix phoenix.server`
> Update the "Up and running" guide

- deployment/I_exrm_releases.md
There was a warning when compiling exrm 0.15.3 
warning: the dependency :exrm requires Elixir ">= 0.15.1 and ~> 1.0.0" but you are running on v1.1.1
> Changed exrm version from 0.15.3 to 0.19.9

- bonus_guides/D_mix_tasks.md
Hey,
I was going through the Up and Running guide and ran into a problem with my non default postgres role password. Having a look in the ecto.create specific part of the documentation I found a whole host of error messages and their resolutions so I thought this might be a good addition?
I've attempted to keep to language similar to that used on description of the other issues.
Thanks,
.FxN
> Added instructions for non default postgres passwords

- bonus_guides/M_custom_errors.md
Confused by the fact that you don't see the error page in dev (I think I'll make a separate PR about that), I added this handling in myself and got an "redefining" warning.
> custom_errors: clarify example

- DD_Plug.md
I was using the Plug guide as a reference and it appeared that `params` would be available in my plug based on this guide. I then got a `function params/0 undefined` error. Changing my plug to reference `conn.params` instead gave me what I was looking for.
There was also a missing `do` at the end of one of the `case` statements.
> Fix incorrect/missing code in find_message plug

- F_templates.md
This is a suggested correction to what appears to be a minor typo in the Templates Guide. The current wording is "commons imports", which should likely read "common imports".
> Minor typo, should likely read "common imports"

- E_views.md
Currently the Views Guide doesn't instruct the reader to restart the server after editing the config/dev.exs file. I think this leads to the error in the attached screenshot. Perhaps we should indicate that the server needs to be restarted in order for the config change to take effect or alternatively use this an opportunity to explain this principle/error message
.
> Mention to restart our server after modifying config

- H_ecto_models.md
This is merely to remove a redundant word. :smile:
Thanks for the excellent docs.
> Removed 'also' because 'as well' is used later.

- CONTRIBUTING.md
- F_templates.md
I noticed the repository name was "phoenix-guides" in CONTRIBUTING.md and changed it.
Also, added a little bit of explanation about the `@` macro in the templates guides.
> Update CONTRIBUTING.md and added description about @ in templates guide

- DD_Plug.md
I was following the guide and the example for "put_headers" produced the error: no function clause matching in Plug.Conn.put_resp_header/3.
I figured this was because the key of the map was an atom, and put_resp_header expects a binary. So I converted to atom to_string and it worked.
If there's a better way to do this, I look forward to hear about that.
- Elixir 1.2.3 on Windows
> Use to_string(k) for put_resp_header

- D_controllers.md
The guide mentions "HTTP Accepts Header" when it should be "Content-Type"
> Fix mention of HTTP header for put_resp_content_type

- bonus_guides/E_using_mysql.md
To workaround an issue with MySQL where `mix ecto.migrate` will run infinitely without feedback. This is very frustrating for beginners. The error is already described here: https://github.com/elixir-lang/ecto/issues/1130. I think this will help a lot of people starting with Phoenix and MySQL.
> updated deps to use mariaex ~> 0.6.1

- introduction/E_installation.md
When following the guides, it wasn't immediately clear how to upgrade Hex when it was allready installed.
It turns out to be the same command, so I added a note in the guides.
kind regards,
Mark
> Add note about upgrading hex

- D_controllers.md
The resulting JSON in this part of the guide isn't valid. Minor syntax fix
> Fix invalid JSON in controllers guide

- H_ecto_models.md
I believe the Ecto repo should use a supervisor and not a worker.
> Use supervisor instead of worker for ecto repo

- G_channels.md
There's an implied notion in the channel guide that you've created a test project with brunch.  When I wasn't able to find the related files the guide spoke of, I didn't have the context that they only came along with the brunch-enabled generator.
This adds a straightforward sentence to the guide that explains that these files are present only in the 'standard' generator, so users have an inkling on why they might not have the same files.  True story. 
Also, bumped jQuery to use the latest  < 1.x version (as of now, 1.11.9)
> Clarifying a hiccup in the guide when using --no-brunch

- D_controllers.md
> Remove postgres-only sentence for Ecto in Controller Guide 'Gathering Data' section

- E_views.md
Leaving in 'recently' might leave people reading this down the road that it is a brand new feature. The first commit where this was added appears to be phoenixframework/phoenix@bad7397f, which was committed Nov 29, 2014.
> Remove 'recently' from ErrorView docs

- deployment/E_heroku.md
We were seeing H15 errors on a production application. Based on a conversation with @chrismccord we figured out that we simply needed to lower the websocket timeout window to less then Heroku's 55 second window. In this case that was 45 seconds. Since this was such an easy fix I thought that the information might be helpful to others. Let me know what you think.
> Note to decrease ws timeout for Heroku deployment

- deployment/E_heroku.md
Heroku Postgres requires SSL when connecting to databases:
https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl
This updates the Heroku deployment guide to instruct users to enable SSL on their Ecto Postgres setup.
> add ssl to heroku database config

- testing/A_introduction.md
I think matches is not clear enough and contains is more understandable in this case.
> Fix unclear wording in test guideline

- A_up_and_running.md
- C_routing.md
- D_controllers.md
- H_ecto_models.md
- bonus_guides/D_mix_tasks.md
- bonus_guides/G_static_assets.md
- bonus_guides/I_sending_email.md
- bonus_guides/P_using_ssl.md
- deployment/E_heroku.md
- deployment/I_exrm_releases.md
- introduction/E_installation.md
Each commit links to the version(unless so tiny I skipped it)
> Several Readme.io suggested edits

- introduction/E_installation.md
In the Introduction > Installation guide, I added a link to the Phoenix Framework `archives` GitHub repo. Readers can follow the link to download the exact Phoenix version they are looking for, including release candidates.
> Provide a link to the .ez archives repo

- deployment/A_introduction.md
In reference to [Issue 467](https://github.com/phoenixframework/phoenix_guides/issues/467) it was mentioned that in the summary production grabbing and compilation of assets was a step in this section:
```
Overall, here is a script you can use as starting point:
```elixir
$ mix deps.get --only prod
$ MIX_ENV=prod mix compile
...
```
But not in the initial part of the guide here or anywhere before:
```
...
This step is required only if you have static assets like images, javascript, stylesheets and more in your Phoenix applications. By default, Phoenix uses brunch, and that's what we are going to explore.
Compilation of static assets happens in two steps:
$ brunch build --production
$ MIX_ENV=prod mix phoenix.digest
Check your digested files at "priv/static".
...
```
So I've added the …
```
> Mention Compilation of Assets for Production Deployment Before Summary

- C_routing.md
When I say `duplicate`, I mean this:
`/reviews/reviews/`
In routing guide, we have codes like this:
scope "/reviews" do
pipe_through [:browser, :review_checks, :other_great_stuff]
resources "/reviews", HelloPhoenix.ReviewController
end
which generates the following paths:
review_path  GET     /reviews/reviews           HelloPhoenix.ReviewController :index
review_path  GET     /reviews/reviews/:id/edit  HelloPhoenix.ReviewController :edit
review_path  GET     /reviews/reviews/new       HelloPhoenix.ReviewController :new
review_path  GET     /reviews/reviews/:id       HelloPhoenix.ReviewController :show
review_path  POST    /reviews/reviews           HelloPhoenix.ReviewController :create
review_path  PATCH   /reviews/reviews/:id       HelloPhoenix.ReviewController :update
PUT …
> Remove duplicate reviews path in routing guide

- H_ecto_models.md
Small change to correct the description of the arity of the Ecto.Changeset cast function. This commit also removes some unnecessary whitespacing from an unrelated line in the same file.
> Corrected description of `cast/3` to `cast/4`.

- deployment/I_exrm_releases.md
Two links in the `advanced deployment` guide currently 404 when clicked on. Replace with working URLs.
> Update Exrm Releases links

- G_channels.md
Hi.
I'm very beginner of phoenix and I found some outdated sample source code in the "channels tutorial", while I followed it.
The url ``code.jquery.com/jquery-1.11.9.min.js`` is now 404 response and should be modified to new one.
> Modified outdated jquery source url

- deployment/I_exrm_releases.md
`exrm` has a recent incompatibility with `mix` that is detailed in [this issue](https://github.com/bitwalker/exrm/issues/326). This update to the guide provides a workaround to that glitch by running `mix compile` before `mix release`.
Note that once the `exrm` issue is resolved, this step can be removed. I had a more verbose explanation of the error in the guide, but figured that the guide should be as clear and simple as possible for new users, so I worked it in as though it's a normal step.
> Add workaround for `exrm` bug

- bonus_guides/S_phoenix_behind_proxy.md
Added some information to the "Phoenix Behind A Proxy" guide, which shows a standard reverse proxy setup ensuring forwarded headers are present.
> Added NGINX config for reverse proxy sockets

- introduction/E_installation.md
In response to #477 this PR adds more explicit instructions for installing erlang on debian-based systems. It's pretty much a copy paste job of the instructions at elixir-lang.org.
That having been said, I think it's worth discussing if we should provide these instructions at all. The guide already say that you should follow the instructions at elixir-lang.org.
> If Erlang was not installed along with Elixir, please see the Erlang Instructions section of the Elixir Installation Page for instructions.
Those instructions are likely to be more up-to-date, so rather than repeating the instructions and taking the risk that these instructions might fall out of sync with the elixir-lang.org instructions maybe we should just omit the command line and leave it at "go over there and follow those …
> add explicit debian instructions. Closes #477

- bonus_guides/EE_custom_primary_key.md
Ecto supports composite primary keys, so we need to explain how to use them.
> Explain composite primary key

- H_ecto_models.md
In relation to #532 I had some time this Friday to dive into this for work. I plan on getting through the whole model guide today, and just figured I'd throw this up for discussion as it goes on.
I took a pretty simple process to go through.
First I just generated a new project after making sure I had Phoenix 1.2/Elixir 1.3 installed. From here, I followed step by step and just updated all code and changes that I saw. There were several issues open that were essentially the changes needed to this guide as a blanket, as well as a few others I saw.
Commit message:
```
Update for Phoenix 1.2 in ecto model guides
This includes issues 529, 530, and 531
Issues Handled:
Issue 529
This brought up the initial concerns about the various pieces that were
later broken into smaller issues after a …
```
> Model Guide Updates (Phoenix 1.2)

- deployment/I_exrm_releases.md
As per https://github.com/bitwalker/exrm/issues/206,
setting the Endpoint.version will trigger code_change during hot upgrade
which will in turn reload the asset manifest.
> Add Endpoint.version for hot upgrades

- testing/E_models.md
I've fixed a few small errors with the model testing guide which would cause certain tests not to pass because they were using incorrect syntax.
> Fixed model testing guide

- bonus_guides/I_sending_email.md
update email guide: Make it clear that the mailgun package is not the only option, not part of Phoenix, and link to some alternatives.
On twitter I saw a new user that was confused and thought that Mailgun was the only option for sending email with Phoenix.
> update email guide: Make it clear that the mailgun package is not the

- testing/J_channels.md
When running `mix phoenix.gen.channel Room rooms`, the generator
fails with the following error message:
```
** (Mix) mix phoenix.gen.channel expects just the module name:
mix phoenix.gen.channel Room
```
This commit updates the channel testing guide to use the source
generated from running the `mix phoenix.gen.channel Room` command.
Also, the `Testing an Asynchronous Push from the Server` section 
references a `handle_out/3` function in the `RoomChannel` which does 
not exist in the generated code. I did not change this section, I wasn't sure
what the appropriate change was.
Includes @jordan0day's changes from #550.
> Update channel testing guide

- DD_Plug.md
This issue has been open for a while, https://github.com/phoenixframework/phoenix_guides/issues/442
I haven't seen anyone disagree with the suggestions in the comments, so I added those in.  If we think something better could be in place, I'm happy to change it.
> Add authenticate/1 and find_message/1 to Plug doc. (#442)

- testing/E_models.md
A few things I came across when going through this guide. Very related to the changes in https://github.com/phoenixframework/phoenix_guides/pull/534.
- `cast/4` is deprecated in favor of `cast/3` + `validate_required/3`
- the first parameter to `changeset/2` is `struct`, not `model`
- the fallback last param for `changeset/2` has changed
> Update models testing to match changes

- bonus_guides/D_mix_tasks.md
> $ mix phoenix.gen.channel Room rooms
> ** (Mix) mix phoenix.gen.channel expects just the module name:
>    mix phoenix.gen.channel Room
>
> $ mix phoenix.gen.channel Room
> ... works
Fixes https://github.com/phoenixframework/phoenix/issues/1907
> Update `gen.channel` sample code

- deployment/I_exrm_releases.md
https://github.com/phoenixframework/phoenix/pull/1838
`. root: "." is no longer required since Phoenix v1.2.`
Not sure about `Mix.Project.config[:version]`. It's missing in https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/config/prod.exs
> Remove root option as it's not compulsory from now

- E_views.md
In the JSON view doc's index should render_many "author.json" and "page.json" instead of render_many "show.json".
> Use "page.json" and "author.json" in View JSON

- H_ecto_models.md
Came across this small redundancy in the docs, so simply removing the first occurrence. 👍
> Remove redundant sentence from ecto-models docs.

- H_ecto_models.md
This is in response to [issue #462](https://github.com/phoenixframework/phoenix_guides/issues/462). A more thorough change might be in order but this patches the issue by adding a link to the anchor tag of the mix tasks guide section for Ecto.
> Add link to Ecto section of mix tasks guide

- bonus_guides/EE_custom_primary_key.md
Guide for custom primary key had invalid code example. The code should had field type as second argument.
> Fix code example for composite keys

- G_channels.md
The channels setup is already using ES2015 and the DOM API has become simple enough to understand now.
> Remove jQuery as a dependency for setting up channels

- .gitignore
- mix.exs
- mix.lock
This is intended for the ex_doc branch.
Rather than duplicating the 'extras' config here, just pick up all the .md files and generate the html so that contributors can preview changes easily.
Also, ignore the generated /doc directory.
Note: this won't work until the .md files are moved under the docs/ directory (which I believe is the plan...)
> Add simple mix.exs to allow previewing guides

- bonus_guides/G_static_assets.md
The documentation was moved out of the main repo, so point the reference to the getting started guide on the website instead.
https://github.com/brunch/brunch/pull/1376
> Fix brunch docs link on the static assets guide

- B_adding_pages.md
- F_templates.md
I find using `Dict` in Phoenix Guides.
`Dict` is deprecated type. So, Removed `Dict` in EEx.
https://github.com/elixir-lang/elixir/commit/94a07df8d3879f8555b75ba4326bc593cc0361b7
Replaced code in Phoenix Guides.
Please, check it.
> Change meta code in eex

- testing/G_controllers.md
I found deprecated code in `this file` at run test.
`warning: using conn/0 to build a connection is deprecated. Use build_conn/0 instead.`
Fix it code.
> Fix deprecated conn, change to build_conn

- G_channels.md
In [Fault Tolerance and Reliability Guarantees](http://www.phoenixframework.org/docs/channels#section-fault-tolerance-and-reliability-guarantees), second bullet point (*Resending Client Messages*):
> Channel clients [...] send them to **the** server [...].
> Add missing "the"

- testing/G_controllers.md
Previously said "pattern much"
> Fix typo to say 'pattern match'

- mix.exs
This sets the preferred environment for `mix docs` so that you do not have to type `MIX_ENV=docs` every time.
> Set preferred environment for mix docs

- docs/controllers.md
- docs/introduction/overview.md
- docs/plug.md
- Use h2's on Plug docs so the items will show in the left-hand menu
- Use relative links to plug.html instead of full urls
> Update headers on Plug docs and fix links

- docs/bonus_guides/sending_email_with_smtp.md
Specifically the bamboo_smtp version that is used in the guide has dependency
issues when trying to install via `mix deps.get`. Using the latest versions still
works with the guide.
> Updates deps version for "Sending Email" guide.

- docs/adding_pages.md
- docs/bonus_guides/custom_errors.md
- docs/bonus_guides/file_uploads.md
- docs/bonus_guides/mix_tasks.md
- docs/bonus_guides/seeding_data.md
- docs/bonus_guides/sending_email_with_mailgun.md
- docs/controllers.md
- docs/deployment/deployment.md
- docs/ecto_models.md
- docs/introduction/installation.md
- docs/routing.md
- docs/templates.md
- docs/testing/testing.md
- docs/testing/testing_controllers.md
- docs/testing/testing_models.md
- docs/up_and_running.md
- docs/views.md
All URLs that previously referenced http://phoenixframework.org for the
pages will no longer be valid when the guides are merged with the
Phoenix repository.
> Use relative urls instead of absolute urls

- lib/mix/tasks/docs.watch.ex
- mix.exs
- mix.lock
`mix docs.watch` will watch for changes, and if any files in the `docs`
directory change, the `mix docs` task will be executed, regenerating the
documentation.
> Add mix docs.watch task for watching markdown files

- docs/bonus_guides/sending_email_with_smtp.md
I believe this may have been a typo? If not then please ignore this PR
> Add app name to the `Email` Module name.

- docs/bonus_guides/sending_email_with_smtp.md
Fixed `defmodule Email do` with `MyApp` prefix.
`mix phoenix.server` complained until I fixed `SYSTEM` to `System`.
> Add missing "MyApp." and s/SYSTEM/System/

- docs/adding_pages.md
- docs/bonus_guides/mix_tasks.md
- docs/controllers.md
- docs/deployment/exrm_releases.md
- docs/ecto_models.md
- docs/routing.md
- docs/testing/testing.md
For whatever reason \`\`\`text blocks revert to single-line mode. Changing  to \`\`\`console fixes it.
Also, mixed character types in directory trees causes the formatter  to revert to single-line mode (Apparently these are different: |│)
> Fix formatting of text blocks

- docs/bonus_guides/static_assets.md
I also came across this confusion https://groups.google.com/forum/#!msg/phoenix-talk/jOKj8Myy5nc/Fj2Dhl_hGJMJ this little bit of documentation hopefully clarifies why some assets do not load unless included in :only option of Plug.Static
> Add some clarification why some static assets won't load

- docs/controllers.md
The present example does not show the plug's welcome message being
overridden like it says so in the text. This new example more clearly
matches the text.
> more clear controllers.md

- docs/deployment/heroku.md
When it's missing, the compilation succeeds and you get very opaque error message. Better to fail sooner with a hint about the cause.
> Fail fast if SECRET_KEY_BASE is missing

- docs/routing.md
As I was running through the guide, as a first time user, I expected that I needed to add  `import HelloPhoenix.Router.Helpers` to the application view. But I didn't have to, so this line might be a bit confusing if you're following along.
> Removing note for importing Router.Helpers

- docs/deployment/heroku.md
Mention that the entire "Adding The Phoenix Static Buildpack" section can be skipped for API only applications in the "Heroku" guide.
The app will fail to compile and deploy if it has the static buildpack without static assets.
This will be helpful for beginners.
> Add note to Heroku deploy guide about static asset buildpack

- docs/ecto_models.md
Adds:
- one internal link (not sure if link will work on the phoenix web site)
- missing parameter in the `mix ecto.gen.repo` command
> Small improvements to the Ecto models guide

- docs/introduction/installation.md
Updates Installation guide as requested in #680.
- References requirements for Elixir 1.4 & Erlang 18+
- Adds example output when Elixir & Erlang have been installed correctly
- Updates phx_new.ez references
Note: I have not updated the Debian specific install instructions.
> add elixir & erlang versions; reference phx_new.ez

- docs/controllers.md
parenthesis => parentheses; 
Removed "and" from a sentence.
> Fixed typos in controllers.md

- docs/bonus_guides/phoenix_behind_proxy.md
Comment on first line of Nginx config breaks Nginx if copied without changes.
It must start from `#`.
> Fix Nginx config comment

- docs/contexts.md
- docs/ecto.md
Shorter headers are easier to read when the docs are published to hex
docs.
Old on the left, new on the right.
> Shorten headers and sub-headers in context guide

- docs/endpoint.md
This fixes some typos I saw when reading through the Endpoint-guide.
> Fix typos in endpoint.md

- docs/bonus_guides/seeding_data.md
Fix syntax issue in a code example that was confusing the syntax highlighter of [the HTML page](https://hexdocs.pm/phoenix/1.3.0-rc.3/seeding_data.html#content).
> Use Elixir comment hash sign instead of C-like //

- docs/contexts.md
The difference between hello and hello_web folder is clear when you
expect it to be in a different folder. But during my first read I missed
it and assumed it would be in _web.
The difference is important and should be pointed out more clearly.
The change is the addition of the sentence: "Note the difference between `lib/hello` and `lib/hello_web`."
> Highlight the different folders

- docs/controllers.md
I believe “PhoenixWeb.Controller” should refer to “Phoenix.Controller”.
> Correcting typo

- docs/bonus_guides/task_supervisor.md
The link to GenStage is broken since it's a reference to when GenStage was experimental
> Fix GenStage link in Running Asynchronous Tasks

- docs/bonus_guides/learning_elixir.md
The current link is for the first version of the book.
> Change Programming Elixir link to newest version

- docs/deployment/heroku.md
As discussed in issue #701, many beginners are surprised to find out later on that Heroku has some serious limitations for Elixir apps. This pull request adds a limitations section to the Heroku guide to help them avoid being bitten down the road.
> Add Heroku limitations section. Resolves #701.

- docs/introduction/overview.md
Made action lower case for format consistency, and added a colon to emphasize that bullet is functioning as a list heading.
> format list of actions under Controllers overview

- docs/deployment/heroku.md
This commit makes sure users don't get any of the
> `mix phoenix.<task_name>` is deprecated. Use `phx.<task_name>` instead."
messages.
> Update Phoenix's deprecated task names

- docs/bonus_guides/using_mysql.md
Since with Elixir 1.4, we no longer need to add the same dependency to dep list and applications list, updating `application` to comply with this rule. 
Reference: https://github.com/elixir-lang/elixir/blob/3002a061468c9bcf58e6e868690439fad339640b/lib/mix/lib/mix/tasks/compile.app.ex#L20
Do correct me if I'm wrong.  Each time I create a new Phoenix webapp I would get the following application
```
def application do
[
mod: {GepDashboard.Application, []},
extra_applications: [:logger, :runtime_tools]
]
end
```
and its different from the documentation and where I do not see `extra_applications` and the same time deps are specified in two places.
> Application inference in Elixir 1.4

- docs/ecto.md
When working through the Ecto guide I stumbled a bit as `Repo` wasn't aliased in the Data Persistence section, so I added it. 
I also fixed a typo along the way. 
Thanks for all the hard work!
> Add missing alias to Ecto guide

- docs/routing.md
On the guide we are starting a new iex session, and we aren't importing HelloWeb.Router.Helpers  nor aliasing HelloWeb.Endpoint.  so we need to call the Endpoint with a full name.
> Fix module call Endpoint as HelloWeb.Endpoint after call 'iex -S mix'

- docs/contexts.md
Just some wrong "lets" where it should be "let's" and a "sigin-in page" that should be "sign-in page".
> fixes typos in contexts.md

- docs/deployment/deployment.md
- docs/deployment/heroku.md
`MIX_ENV` is not used by `mix phx.digest` in any way.
> Remove MIX_ENV=prod from mix phx.digest commands

- docs/contexts.md
Just a pair of details I stumbled upon when following this guide:
* The `views` attribute should not be writable by the author, and needs a default.
* The `edit` action can also benefit from the `:authorize_page` plug.
> Contexts guide corrections

- docs/introduction/overview.md
As a new Phoenix developer I needed to understand that "endpoint" is the boundary that separates external from internal requests. The endpoint isn't, as the name might imply, where requests terminate. It's called "endpoint" because that's as far as the external requester can go before it has to wait for the Phoenix app to process the request and respond. From the Phoenix developer's point of view the endpoint is more like the beginning than the end!
> Clarify endpoint concept

- docs/routing.md
The Router guide mentions match/3 - should be match/5
https://hexdocs.pm/phoenix/Phoenix.Router.html#match/5
> Issue 472 - fix references to match/3 in router guide

- docs/channels.md
Closes #337
Heavily based on the work done by @willykaram and @lancehalvorsen in this PR: https://github.com/phoenixframework/phoenix_guides/pull/458/files#diff-d34b16f937de2bf0f676d573c7c122f5
I added bolding around the Step titles as well.
Convention also seems to be to use one space after the end of a sentence, so I fixed a sentence elsewhere in the file.
> add guide for using sockets with token auth

- mix.exs
- mix.lock
Closes https://github.com/phoenixframework/phoenix_guides/issues/623
Should now generate an epub file with all of the docs in addition to the regular HTML.
> Generate epub docs

- CONTRIBUTING.md
- docs/phoenix_mix_tasks.ex
- docs/routing.md
- docs/testing/testing_controllers.md
- docs/views.md
For consistency, sentences with two spaces following the end have had one of the spaces removed.  
This could also held off on until the changes for today have been made.
Should this be added to CONTRIBUTING.md though?
> remove extra space following end of sentences
