C_routing.md
Added plug :protect_from_forgery and some spelling fixes throughout the doc.
=> plug :protect_from_forgery addition, spelling

E_views.md
- fixes misc. wording issues
- adds section presenting the ErrorView
=> Rendering in views

0_overview.md, A_up_and_running.md, B_adding_pages.md
- text changes
- code block additions
- misc fixes that make me itch less
Refurbishment for more files coming soon.
=> First Batch of Updates for v0.8.0

B_adding_pages.md, C_routing.md, X_mix-tasks.md
- much re-writing, additions, and subtractions to make the guide match up with Phoenix v0.8.0
- small refurb changes suggested by phoenixframework.org
=> Router Refurb for 080

D_controllers.md
- reworking for 0.8.0
- adding code blocks for actions
- lots of re-wording
=> Controller Refurbishing for 0.8.0

E_views.md
- changes for Phoenix v0.8.0
- wording changes
- fixes for incorrect instructions
=> Refurbish View Guide for Phoenix v0.8.0

F_templates.md
- refurb for 080
- wording changes
- guide links added
I'll move this over to phoenixframework.org as soon as I merge.
//cc @jeregrine @chrismccord
=> Refurb Template Guide for 0.8.0

K_deployment.md
- refurb for 0.8.0
- lots of re-wording
- re-work and re-position the exrm commands section
=> Refurb Deployment Guide for 0.8.0

G_channels.md
Currently this is a WIP with lots of work yet to do. I did want to bring some early visibility to this for anybody who is interested. // @chrismccord
I'm aiming to accomplish several things with this:
- break the explanation into small pieces that build logically on what has come before
- bring a sense of experimentation and verification to building the examples
- work as much as possible in iex to remove the need to build out a client
=> New Channel Guide

A_up_and_running.md, B_adding_pages.md, F_templates.md, H_ecto-models.md, K_deployment.md
- updating phoenix version number references
- suggestions from phoenixframework.org
=> Small Edits for 0.9.0

C_routing.md
While reading the section on routing as a (native English), I made a number of corrections and fixed some typos which I believe will improve the overall readability of the text. Hopefully I didn't mess up any of the technical details, but ran the code to double-check so think it's alright.
=> Routing update and overall improvements.

D_controllers.md
Here are some minor changes and additions to the controllers section which I hope will improve the readability and consistency of the text.
I hope you don't get angry at my nit-picking so feel free to veto any proposed changes you feel are inappropriate.
One comment: I found the last part about aliasing helpers unclear and was unable to understand it as a newbie.
I'm referring to the end which starts with the text:
```
We can also make use of the path helpers we learned about in the Routing Guide. It's useful to 
alias the helpers in order to shorten the expression.
```
=> Some minor changes and additions - Controllers

B_adding_pages.md
- re-writing all the `use` constructs
- removing references to the main view
- editing the file trees
=> changes to reflect v0.10.0

E_views.md
- remove mentions of the main view
- change references to the 'use' line
- re-wording to accommodate changes for 0.10.0
=> Refurbish the View Guide for 0.10.0

X_mix-tasks.md
- changes to phoenix.new for v0.10.0
- add phoenix.gen.resource
- add documentation for ecto mix tasks
- add documentation for creating an application specific mix task
closes #12
=> Refurbish Mix Task Guide for v0.10.0

E_views.md
- remove section about rendering an error template through the application layout
- add a complete html document as the error template instead
- reword some sections
=> Rework ErrorView Section of View Guide

E_views.md, G_channels.md, H_ecto-models.md, K_deployment.md
=> Suggested Edits from the Site

E_views.md
Looks like something changed between versions of Phoenix and some outputs where not updated
=> Update inconsistencies in E_views.md

H_ecto-models.md
Complete top-to-bottom re-write to reflect all the changes in ecto over the last couple of months.
I'm going to let this simmer here for a day or so before I push it to the site. Comments welcome!
=> Re-write the Ecto Models Guide

G_channels.md
Corrected "JavaScript"
Corrected source code example (missing closing quotes)
=> Copy fixes

A_up_and_running.md, K_deployment.md
- reflect protocol consolidation changes
- bring up the upcoming digest mix task
- general re-wording
=> Refurb Deployment Guide for Elixir 1.0.4

DD_Plug.md
I brain dumped this out, so excuse any errors :)
We need to give plug proper justice, and I hope this is a step in the right direction. Feedback appreciated before we copy over. Thanks!
=> Plug guide

X_mix-tasks.md
The name of the mix task changed. This just updates the guide to reflect the change.
=> phoenix.gen.resource => phoenix.gen.html

H_ecto-models.md
This is the only thing in your edit missing from my last PR.
=> Fix typo  in H_ecto-models.md

0_overview.md, A_up_and_running.md
- add Dependencies section to the Overview Guide
- ask users to read it before they begin in Up And Running
This closes #210 .
=> Be Explicit About Dependencies

H_ecto-models.md
I re-wrote an extended suggestion from the site helping people who might want to use MySQL instead of PostgreSQL.
=> Switching to MySQL

B_adding_pages.md, C_routing.md, DD_Plug.md, D_controllers.md, E_views.md, G_channels.md, H_ecto-models.md
Changes were taken from newly generated Phoenix 0.12 application.
=> Update definitions for Router and PageView.

D_controllers.md
This handles part of an issue originating from the Phoenix repo:
https://github.com/phoenixframework/phoenix/pull/818#issuecomment-96848710
closes #212
=> Clarify Relationship Between Controllers and Plug

D_controllers.md
This originated here: https://github.com/phoenixframework/phoenix/pull/818#issuecomment-96848710
closes #211
=> Add Example of `send_resp/3`

E_views.md
Some minor changes have happened so updated the guide to match what we get from latest version.
=> Use code (for examples) from latest phoenix version

H_ecto-models.md
Task `mix phoenix.gen.html` also generates a model and a controller tests.
=> Note that phoenix.gen.html also generates test files.

L_advanced_deployment.md
- switch to creating a production release
- add new applications to bundle and start
=> Rework Advanced Deployment Guide

A_up_and_running.md, L_advanced_deployment.md
Closes https://github.com/phoenixframework/phoenix_guides/issues/250
Let me know if there's anything I missed!
=> Bump up archive and mix versions for 0.13.1

A_up_and_running.md, X_mix-tasks.md
- Changes reflecting new phoenix.new dependency installation prompt for Up and Running + Mix Tasks Guides
=> Show New Dep Install Prompt From phoenix.new

K_deployment.md, Y_help.md
Other file fixes a misspelling.
=> 'phoenix.digest' is now in a stable release

styling/Phoenix_files/_hero.scss
This rule shouldn't be included in the css.
=> Add note about logo rule

X_mix-tasks.md
I have created a mix phoenix.gen.json documentation in the Mix Tasks section.
=> Mix phoenix gen json

X_mix-tasks.md
=> Updates for mix tasks guide

C_routing.md, D_controllers.md, E_views.md, Z_resources.md
Various and sundry edits and fixes suggested by phoenixframework.org users.
=> Suggested Edits

DD_Plug.md
Switches the authentication and authorization error messages.
=> Suggested Edit for Plug Guide

testing/A_introduction.md, testing/E_models.md
This is the first full version of the guide.
=> Model Testing

D_controllers.md
It was pointing to the wrong file.
=> Fix path in Assigning Layouts section.

E_views.md
The link was pointing to a non-existing anchor. I've fixed that.
=> Update link to Template Guide.

introduction/A_overview.md, introduction/E_installation.md
The intention here is to improve readability. I hope that I haven't misrepresented anything by these changes.
/cc @josevalim
=> Wording Changes for Overview

C_routing.md
closes #299 
ref phoenixframework/phoenix#989
=> Fully Qualify the Phoenix.Transports.WebSocket Module References

bonus_guides/H_file_uploads.md
You've been waiting for this one a long time, @chrismccord. :)
Edit:
closes #98
=> First version of the File Upload Guide.

testing/A_introduction.md
A user new to the project may not have Postgres running or the postgres role configured.
Move the note up to the point at which the tests will fail in that case, and link to the relevant info.
=> Link to the Mix Tasks guide for information on the test database.

H_ecto_models.md
So I spent way too much time trying to beat callbacks into working in some app I'm working on. I couldn't find a guide to do this, so I wrote up this section after I figured it out.
=> added section on working with lifecycle callbacks

A_up_and_running.md, introduction/E_installation.md
I added an extra section to Up and Running which should clarify this further, but I left it as a second commit in case it might lead to more issues.
Thoughts, @chrismccord?
closes #326
=> Clarify Elixir/Erlang Dependency Installation

C_routing.md
Mostly, this involves changing lines like this:
user_path  GET     /users           HelloPhoenix.UserController.index/2
To this:
user_path  GET     /users           HelloPhoenix.UserController :index
=> Fix phoenix.routes output to match Current

C_routing.md, G_channels.md, bonus_guides/D_mix_tasks.md, testing/J_channels.md
@lancehalvorsen ready for review/edits
=> Channels Bump for 0.15

deployment/A_introduction.md, deployment/E_heroku.md
* We talk about secrets
* We talk about assets
* We provide an overall script to be used in prod
This needs to wait for the next Phoenix release because I use the new `mix phoenix.gen.secret`.
=> Extend the deployment guide

bonus_guides/G_static_assets.md
My attempt to describe asset management in Phoenix
https://github.com/phoenixframework/phoenix_guides/issues/246
=> Static Assets Guide

G_channels.md
I believe that's the place to go to find out how to authentication sockets and channels. It took me a while to stumble upon it, when I was trying to figure it out.
=> Link to Phoenix.Token for more information on Socket & Channel Authentication

deployment/E_heroku.md
Minor upgrade of the guide needed due to the recent changes of Ecto.
Also took the opportunity to add the Heroku Postgres add-on URL.
=> Update Heroku guide with latest Ecto option, Heroku add-on URL

H_ecto_models.md
Ecto now supports a bunch of adapters for various DBs.
=> Upgrade Ecto's supported DBs. Fixes #350

H_ecto_models.md
~~I only followed the guide till "Data Relationship and Dependencies" so maybe that part also has something that's a bit out of date. Will try to look at it soon but in the meantime this is ready~~ :)
Besides some text changes/dup word removals I also updated console/code output as they appear in latest Phoenix (1.0.2).
=> Update Ecto models guide

introduction/L_community.md
- re-ordered items to emphasize discussion and try to head off user questions landing in the issue tracker.
- added links, fixed capitalization.
=> Update community guide

H_ecto_models.md, bonus_guides/E_using_mysql.md, bonus_guides/I_sending_email.md, deployment/I_exrm_releases.md
Just thought it'd be nice to use up to date versions :)
=> Update deps versions across guides

bonus_guides/EE_custom_primary_key.md
Added the info from @josevalim response about how to get around this issue.
=> issue 1214

bonus_guides/D_mix_tasks.md, deployment/A_introduction.md, testing/J_channels.md
As discussed with @lancehalvorsen; https://github.com/phoenixframework/phoenix_guides/pull/378#discussion_r40031477
=> Remove instances of "your" referencing files or replace them with "the"

G_channels.md
I set out to update the channels guide, but here are some minor fixes to the current one first.
=> Minor fixes in the channels guide

deployment/E_heroku.md
I tried to clarify the Heroku guide a bit.
- Don't start by copying the contents of `config/prod.secrets.exs` to `config/prod.exc` and then completely rewrite it, but simply add the required lines in one go.
- Put the `secret_key_base`-configuration in the existing config block
- Don't use "A_LONG_STRING_WILL_BE_PRINTED"/"my_secret_key_base", but use an example key
- Write a nicer commit message
Here's a demo app of the guide's exact end result (to update the guide with later): https://github.com/jeffkreeftmeijer/phoenix_heroku_example
=> Clarifications to the Heroku guide

B_adding_pages.md, bonus_guides/D_mix_tasks.md
A new phoenix project does not use scss, but uses css.
`app.scss` --> `app.css`
=> Update example tree of default app.

testing/E_models.md
I've updated the models testing guide to make sure file contents and console output is accurate. I haven't checked the "Generating an HTML Resource"-section yet (I need to build another example app for that), but I hope to get to that soon.
* Remove compile and generation lines. Now the output matches the output
you'd get after having compiled before, like the test output in the
testing introduction guide.
* Update the test counts. The testing introduction guide leaves the user
with an app that has sixteen tests now, so this guide is working from
there.
* Add module lines around code blocks (like `defmodule HelloPhoenix.UserTest do`
and `end`) to add context and indent accordingly.
* Add the changes in UserController as an explicit step instead of a
note to prevent test failures later in …
=> Update the model testing guide

deployment/E_heroku.md
Hi! I just have a few little tweaks based on the heroku deploy I just did; I found a few small differences between what the guide said and what I actually needed to do/what actually happened.
Overall, though, everything went great!!! :tada: :balloon: :fireworks:
=> Heroku fixes

D_controllers.md
=> Fix link to dets.

D_controllers.md
These double quotes should not be in the file content.
=> Remove unnecessary double quotes

introduction/E_installation.md
little tip to prevent https://github.com/phoenixframework/phoenix/issues/1411
=> tip to prevent issues on debian based distros

bonus_guides/F_config.md
@lancehalvorsen this is a suggested Config Guide to address Issues #19. Please LMK if you have any feedback and I'll revise accordingly.
=> Proposed Config Guide

C_routing.md
I've adjusted the the nested scope referenced as discussed in #439. Apologies I made a sloppy error while squashing, and it was just easier to create a new PR than clean-up the error.
=> Adjusting nested scopes examples in Routing Guide

G_channels.md
Why?
- It's important to understand failure semantics when deploying a distributed system. The guides don't currently have any documentation on these semantics. 
This change addresses the need by:
- Describing the failure semantics for subscriptions, channel crashes, and messages.
=> Add failure semantics section to Channel guide

E_views.md
Updated Phoenix.Endpoint.ErrorHandler to Phoenix.Endpoint.RenderErrors as per Phoenix 1.14 code.
=> Changed ErrorHandler to RenderErrors

A_up_and_running.md
The console outputs on the getting started page are a bit outdated.
It's not a big deal, but still, it could cause some confusion.
I updated them with the current outputs.
kind regards
Mark
=> Update console outputs

bonus_guides/V_learning_elixir.md
Some readers might be interested in these.
=> Add Screencasts to "Learning Elixir" Guide

deployment/E_heroku.md
A really small fix to get the documentation up to date with the changes introduced here: https://github.com/phoenixframework/phoenix_guides/pull/491
=> Add note to commit websocket timeout changes

A_up_and_running.md
=> Remove duplicate word

deployment/E_heroku.md
In reference to [Issue 508](https://github.com/phoenixframework/phoenix_guides/issues/508) I have just added a single line to commit the Procfile so that Heroku deployment will complete properly if the guide is followed exactly.
=> Add Procfile to Git for Heroku Deployment

H_ecto_models.md
=> Add short note about postgres db setup

deployment/E_heroku.md
https://github.com/phoenixframework/phoenix/issues/1730#event-673287024
cc @josevalim
=> Include documentation for POOL_SIZE

testing/E_models.md
Corrected `ModuleCase.errors_on/2` to `ModelCase.errors_on/2`.
=> Corrected `ModuleCase.errors_on/2` to `ModelCase.errors_on/2`.

deployment/E_heroku.md
Performed small copy edits and used console example for setting POOL_SIZE environment variable for mix task.
=> Expand content on POOL_SIZE in Heroku guide

C_routing.md
Updated the indentation where routes are displayed
**before:** 
**after:**
=> Add indentation for readability

bonus_guides/D_mix_tasks.md
...so you can access Repo etc.
=> Add information on how to start your application from custom mix task

bonus_guides/X_seeding_data.md
This is a draft of the Bonus Guide on Seeding Data mentioned in issue #376.
@chrismccord @lancehalvorsen please LMK if you have any feedback and I can revise as needed.
=> Draft of Seeding Data Guide

G_channels.md
`mix phoenix.new` generates a `user_socket.ex` with `room` not `rooms`.
```ex
```
=> Update from rooms to room

C_routing.md
It wasn't a complete sentence. Let me know if there is any better word and I am happy to change.
Great job here, guys! 👍
=> Fix missing verb for Plug.Parsers in Routing.

H_ecto_models.md
Possible the guide should be reviewed more throughly, since the's some duplicated content. Maybe this one should refer to the ecto guide and only focus on what is special for phoenix? But that is probably a bigger rewrite.
=> Link to Ecto getting started guide in the phoenix ecto guide

E_views.md
I added the MVP version of what a JSON section of the View docs might look like.
https://github.com/phoenixframework/phoenix_guides/issues/438
=> Add JSON guide to View docs

bonus_guides/G_static_assets.md
Add information on third-party library loading using globals according to Brunch guide (https://github.com/brunch/brunch-guide/blob/master/content/en/chapter05-using-third-party-registries.md).
=> Update G_static_assets.md - Add information about global libraries

bonus_guides/X_seeding_data.md
Just some small fixes I noticed while reading through.
=> Updating seeding data docs example

testing/G_controllers.md
This covers testing an API controller, there is nothing in here
for feature test style tests.
Makes progess on https://github.com/phoenixframework/phoenix_guides/issues/99 , but doesn't close.
=> Add Controller Testing Guide (#99)

deployment/E_heroku.md, introduction/E_installation.md
Was reading through the guides and just spotted a couple minor typos, so I thought I would address them 😄
=> fix minor misspellings in installation and heroku

B_adding_pages.md
- Mention that phoenix now creates the `templates` directory
- Update listed file structure to properly show files generated by brunch
- Update listed file structure to properly show files generated by Phoenix itself
I'm working on going through the guides from 0 to catch small errors/notes. This is one of the first ones and I plan on proofing the rest too (slowly but surely).
Sidenote: Is there a roadmap for updating guides to 1.3? Didn't see any PR's up that were WIP on it and would be happy to start working on that as the new structure etc changes quite a lot.
=> Update B Adding Pages

H_ecto_models.md
This one paragraph was a bit hard to parse - I hope this is an improvement.
Many thanks for writing these guides (Hi Lance!)
=> Small wording change on an excellent tutorial.

docs/bonus_guides/learning_elixir.md, docs/channels.md
This PR cleans up some of the obvious cases for #616.
=> Cleaning up some list syntax errors.

docs/channels.md
Hey!
After discussing with the author of the currently referenced library [here][discussion-link], I was advised to start a new initiative, since that repository is no longer maintained.
I have a vested interest in maintaining a solid C# client, since I am shipping it with my Unity game. Hence, I started a new project and would like to give it more exposure to attract contributions for enhancing the library.
Overall, the main gains of this new library for the phoenix community are summarized in the following:
1. An active project which encourages contributions
2. A more friendly, statically-typed API
3. Ships with unit and integrations tests
4. Slightly better documentation
5. Full Unity support
[discussion-link]: https://github.com/jfis/dn-phoenix/issues/3
=> Update C# client link

docs/bonus_guides/sending_email_with_smtp.md
Helps to clarify potential confusion, e.g. #634.
=> Link to docs for `new_email/1`

docs/routing.md
This addresses the comment left by @Gazler in https://github.com/phoenixframework/phoenix_guides/pull/628
=> Add link to Phoenix.Router resources function (amended)

docs/controllers.md
This addresses the comment left by @Gazler in https://github.com/phoenixframework/phoenix_guides/pull/633
=> Modified url for highlighting correct lines (amended)

docs/controllers.md
Modified url for highlighting correct lines as the range given previously was not pointing the correct lines.
=> Modified url for highlighting correct lines

docs/bonus_guides/phoenix_behind_proxy.md, docs/bonus_guides/using_ssl.md, docs/deployment/deployment.md, docs/deployment/exrm_releases.md, docs/deployment/heroku.md
Brings guides in line with phoenixframework/phoenix/pull/2086.
=> Update manifest.json filename references

docs/controllers.md
Fixes a small typo in the controllers documentation
=> Fix controllers documentation typo

docs/controllers.md
Closes issue https://github.com/phoenixframework/phoenix_guides/issues/660
=> Remove incorrect sentence

docs/routing.md
I think we want "by" to be "with" here.
=> Fix wording

docs/controllers.md
I took the liberty to tackle this, it should cover the first two checks in the controller section for 1.3 changes.
=> controllers -> namespaces and conventions

docs/introduction/installation.md
Is it ok for me to continue doing some minor changes that I can help with? Or should I ask for permission to do a change in case someone has it already?
=> installation :: phoenix ~> phx

docs/plug.md
Shouldn't we move the pipes to newlines as well?
=> Plug :: Null arity function calls

docs/plug.md
As mentioned in https://github.com/phoenixframework/phoenix_guides/issues/680
=> Add parenthesis to calls to halt()

docs/plug.md
Changed "lets write" to "let's write".
=> Fixed typo in plug.md.

docs/templates.md
Updates Templates guide for 1.3
* add web namespaces
* update file path locations
Maybe we should add todo items for the templates guide in #680.
=> Update Template Guide for 1.3

docs/contexts.md
* "Let's found out why" -> "Let's find out why"
* "design decisions done throughout the guide" -> "design decisions made throughout the guide"
=> Fix minor typos

docs/endpoint.md
Suggested rewording, for clarity.
=> Minor rewording

docs/templates.md
* Updated the reference to web.ex to hello_web.ex to reflect the new structure change in the phoenix project.
* Also updated the view imports to reflect how it looks in a vanilla phoenix project.
=> Updated web.ex file to reflect new directory structure in template guide.

docs/contexts.md
=> Found 2 typos in the context guide

docs/controllers.md
Ecto Models Guide => Ecto Guide
=> fix ecto guide url

docs/adding_pages.md
`hello.ex` and `hello_web.ex` are inside of `lib`.
=> update directory structure

docs/up_and_running.md
Message outdated after running `mix phx.new hello`.
=> update welcome message

docs/bonus_guides/using_mysql.md
Hi!
Tiny update, changes `mix phoenix.gen` to `mix phx.gen` in mysql setup bonus guide
Don't think I can create a branch on the phonenix_guides repo, so that the pull request is not to master, but to a branch?
Tried following the  guidelines:(https://github.com/phoenixframework/phoenix_guides/blob/master/CONTRIBUTING.md).
=> update generate new app command to phx

docs/testing/testing.md
Update mix task to use phoenix 1.3.  mix phx.gen.html ..... also, update the results.
=> Update mix phoenix.gen.html to 1.3 and update results.

docs/channels.md
Just update phoenix.js link from 1.2 to 1.3.
=> Fix phoenix.js link

docs/contexts.md
While I was reading whole guide, I've tried to fix:
- update code snippets that comes from generator
- fix typos
- improve readability in few places
I'm not native speaker, so I've not check grammar.
=> Improve context guide

docs/adding_pages.md, docs/bonus_guides/learning_elixir.md, docs/bonus_guides/task_supervisor.md, docs/introduction/learning.md, docs/testing/testing.md, docs/views.md
Closes #785 and conflicts heavily with #773 
Also fixed a minor capitalization discrepancy.
=> Link to latest Supported Elixir

docs/routing.md
=> Adding a line about using the Conn over the Endpoint

docs/introduction/overview.md
The flow of the document jumped around bit.
- mention of Phoenix external layers.
- overview of internal Phoenix parts.
- a more detailed look at the external layers.
The new structure.
- overview of internal Phoenix parts.
- makes more clear where Phoenix sits in the ecosystem.
- smoothly transitions between the three layers.
=> edit for clarity and flow

docs/bonus_guides/mix_tasks.md
=> Add link to ecto alter/2 function

docs/channels.md
closes #148 
Not sure how good my wording is on it.
=> reference Redis PubSub adapter in channels guide

docs/bonus_guides/custom_primary_key.md, docs/bonus_guides/file_uploads.md, docs/bonus_guides/mix_tasks.md, docs/bonus_guides/seeding_data.md, docs/channels.md, docs/controllers.md, docs/introduction/installation.md, docs/introduction/overview.md, docs/templates.md, docs/testing/testing_channels.md
This PR is a work in progress.
Working to resolve Issue 707 (https://github.com/phoenixframework/phoenix_guides/issues/707) - removing references to Ecto Models.
-  testing models <- handled in https://github.com/phoenixframework/phoenix_guides/issues/721
- testing controllers <- handled in https://github.com/phoenixframework/phoenix_guides/issues/721
=> Issue 707 - Remove Ecto Model references

docs/adding_pages.md, docs/channels.md, docs/controllers.md, docs/ecto.md, docs/introduction/community.md, docs/introduction/installation.md, docs/introduction/learning.md, docs/introduction/overview.md, docs/phoenix_mix_tasks.ex, docs/routing.md, docs/testing/testing_channels.md
This is a follow up to #755 where I was asked by @Gazler to avoid changing the `styling` folder.
The switch to https is a trivial change compared to other major fixes, hence no very high priority here. It should be an easy merge though.
=> Prefer https over http when possible

docs/channels.md
=> add note on N+1 query in handle_out
